name: weather

on:
 pull_request:
  brances: ['*']

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - env: 
          PR_NAMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$(curl "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,relativehumidity_2m,windspeed_10m")

          gh pr comment $PR_NAMBER --body "WEATHER" --repo $GITHUB_REPOSITORY