name: PR Comment

on:
 pull_request:
  brances: ['*']

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - env: 
          PR_NAMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          gh pr comment $PR_NAMBER --body "The weather" --repo $GITHUB_REPOSITORY